import React, { useState } from 'react';
import { Copy, Sparkles, Terminal, ChevronDown } from 'lucide-react';
import { Theme } from '../types';

interface AICodingProps {
  theme: Theme;
}

const AI_CODING_PROVIDERS = [
  { name: 'Copilot', id: 'copilot', color: 'text-purple-500', description: 'GitHub Copilot' },
  { name: 'CodeGemma', id: 'codegemma', color: 'text-green-500', description: 'Google CodeGemma' },
  { name: 'Code Llama', id: 'codellama', color: 'text-blue-500', description: 'Meta Code Llama' },
  { name: 'DeepSeek', id: 'deepseekcoder', color: 'text-red-500', description: 'DeepSeek Coder' },
];

const CODE_LANGUAGES = [
  'JavaScript', 'Python', 'Java', 'C++', 'TypeScript', 'HTML', 'CSS', 'SQL'
];

export const AICoding: React.FC<AICodingProps> = ({ theme }) => {
  const [prompt, setPrompt] = useState('');
  const [language, setLanguage] = useState('JavaScript');
  const [selectedProvider, setSelectedProvider] = useState('copilot');
  const [generatedCode, setGeneratedCode] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setGeneratedCode('');

    // Simulate API call
    setTimeout(() => {
      const codeSnippet = `// Generated by ${AI_CODING_PROVIDERS.find(p => p.id === selectedProvider)?.name} for language: ${language}
// Prompt: ${prompt}

function greet(name) {
  console.log(\`Hello, \${name}!\`);
}

greet('World');`;
      setGeneratedCode(codeSnippet);
      setIsGenerating(false);
    }, 2000);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const promptSuggestions = [
    "Create a React component for a login form",
    "Write a Python script to scrape a website",
    "Generate a SQL query to find all users over 30",
    "Implement a binary search algorithm in Java",
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-bg-dark dark:to-slate-900 pt-20">
      <div className="max-w-6xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold font-display bg-gradient-to-r from-brand-start to-brand-end text-transparent bg-clip-text mb-4">
            AI Code Generator
          </h1>
          <p className="text-lg text-slate-600 dark:text-slate-400">
            Generate code snippets in various languages with AI
          </p>
        </div>

        {/* Provider Selection */}
        <div className="mb-8">
          <h3 className="text-sm font-semibold text-slate-500 dark:text-slate-400 mb-3 uppercase tracking-wide">
            Choose AI Provider
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {AI_CODING_PROVIDERS.map((provider) => (
              <button
                key={provider.id}
                onClick={() => setSelectedProvider(provider.id)}
                className={`p-4 rounded-lg border transition-all duration-200 text-left ${selectedProvider === provider.id
                  ? 'border-brand-end bg-brand-end/10 text-brand-end'
                  : 'border-slate-200 dark:border-slate-700 hover:border-brand-start dark:hover:border-brand-start'
                  }`}
              >
                <div className={`text-sm font-medium ${provider.color} mb-1`}>
                  {provider.name}
                </div>
                <div className="text-xs text-slate-500 dark:text-slate-400">
                  {provider.description}
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Generation Interface */}
        <div className="bg-white dark:bg-slate-800 rounded-xl shadow-lg p-6 mb-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                What do you want to code?
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g., 'A function to calculate Fibonacci sequence...'"
                className="w-full h-32 px-4 py-3 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-brand-end resize-none"
              />
            </div>
            <div className="flex flex-col gap-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                  Language
                </label>
                <div className="relative">
                  <select
                    value={language}
                    onChange={(e) => setLanguage(e.target.value)}
                    className="w-full px-4 py-3 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-brand-end appearance-none"
                  >
                    {CODE_LANGUAGES.map(lang => <option key={lang} value={lang}>{lang}</option>)}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 pointer-events-none" />
                </div>
              </div>
              <div className="flex-grow flex items-end">
                <button
                  onClick={handleGenerate}
                  disabled={!prompt.trim() || isGenerating}
                  className="w-full px-6 py-3 bg-brand-end text-white rounded-lg hover:bg-brand-end/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
                >
                  {isGenerating ? (
                    <>
                      <Sparkles className="animate-spin" size={20} />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Terminal size={20} />
                      Generate Code
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>

          {/* Prompt Suggestions */}
          <div className="mt-4">
            <p className="text-sm font-medium text-slate-500 dark:text-slate-400 mb-2">
              Need inspiration? Try these prompts:
            </p>
            <div className="flex flex-wrap gap-2">
              {promptSuggestions.map((suggestion, index) => (
                <button
                  key={index}
                  onClick={() => setPrompt(suggestion)}
                  className="px-3 py-1 text-xs bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 rounded-full hover:bg-brand-start/10 hover:text-brand-start transition-colors"
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Generated Code */}
        {(generatedCode || isGenerating) && (
          <div>
            <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-4 flex items-center gap-2">
              <Terminal size={20} />
              Generated Code
            </h3>
            <div className="bg-gray-900 rounded-lg shadow-lg overflow-hidden">
              <div className="flex justify-between items-center px-4 py-2 bg-gray-800">
                <span className="text-sm text-gray-400">{language}</span>
                <button onClick={handleCopy} className="flex items-center gap-2 text-sm text-gray-300 hover:text-white transition-colors">
                  <Copy size={16} />
                  {copied ? 'Copied!' : 'Copy'}
                </button>
              </div>
              <div className="p-4 overflow-x-auto">
                {isGenerating ? (
                  <div className="flex items-center justify-center h-48">
                    <Sparkles className="animate-spin text-brand-start" size={32} />
                  </div>
                ) : (
                  <pre><code className={`language-${language.toLowerCase()}`}>{generatedCode}</code></pre>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Info */}
        <div className="mt-8 text-center text-sm text-slate-500 dark:text-slate-400">
          <p>Currently showing placeholder code. In a real implementation, this would connect to actual AI code generation APIs.</p>
        </div>
      </div>
    </div>
  );
};